POST localhost:8080/schedules
Content-Type: application/json

{
  "content1": "안녕하세요"
}

###
GET localhost:8080/schedules/1

###
GET localhost:8080/schedules

###
DELETE localhost:8080/schedules/1

###
PUT localhost:8080/schedules/1
Content-Type: application/json

{
  "content": "안녕하세요2"
}

### Comment 생성
POST localhost:8080/comments
Content-Type: application/json

{
  "content": "123",
  "scheduleId": 2
}

###
GET localhost:8080/comments/1